### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Ichunjo** [Ichunjo/PyonFX#1]
- [x] Speed up the font module
Using caching really boosted it
- [ ] Resolve numpy typing bugs with mypy. Basically all the `type: ignore[var-annotated]` comments
- [ ] Remove numpy calls where pure python is good enough and probably faster
- [ ] using typing.Self when possible once mypy will support it
- [ ] Same for match case statement
- [ ] Remove useless things in type module
- [ ] Do something about the things in utils
- [ ] Add more customised exceptions and warnings

Tests:

- [ ] Make tests for the font module
- [ ] Make more tests for core module
- [ ] Make tests for colourspace module
- [ ] Make test for convert module
- [ ] Make tests for image module
- [x] Make tests for shape module
- [ ] Make tests for utils module
